temperature: 0.0001
device: 0
normal-th: 5
fraud-th: 85
consis-weight: 1.5
weight-decay: 0.00001
trainable-weight-decay: 0.0
model: 'backbone'
hidden-dim: 64
num-layers: 1
input-drop: 0.0
hidden-drop: 0.0
mlp-drop: 0.3
drop-ratio: 0.2
mlp12-dim: 128
mlp3-dim: 128
bn-type: 2
data-set: 'amazon'
batch-size: 32
unlabel-ratio: 6
training-ratio: 1
shuffle-train: True
to-homo: False
optim: 'adam'
lr: 0.001
runs: 1
epochs: 30
trainable-optim: 'adam'
trainable-lr: 0.01
num_iters: 128
store-model: True
model-path: "./output"
seed: 42
early-stop: True